//AUTOGENERATED FILE FROM png2asset
// Conversion args: TitleScreen.png -c TitleScreen.c -map -noflip

#ifndef METASPRITE_TitleScreen_H
#define METASPRITE_TitleScreen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define TitleScreen_TILE_ORIGIN 0
#define TitleScreen_TILE_W 8
#define TitleScreen_TILE_H 8
#define TitleScreen_WIDTH 160
#define TitleScreen_HEIGHT 144
#define TitleScreen_TILE_COUNT 122
#define TitleScreen_PALETTE_COUNT 3
#define TitleScreen_COLORS_PER_PALETTE 4
#define TitleScreen_TOTAL_COLORS 12
#define TitleScreen_MAP_ATTRIBUTES 0
extern const unsigned char TitleScreen_map[360];
#define TitleScreen_map_attributes TitleScreen_map

BANKREF_EXTERN(TitleScreen)

extern const palette_color_t TitleScreen_palettes[12];
extern const uint8_t TitleScreen_tiles[1952];

#endif
